### ISSUE TITLE
expose `chars`

### ISSUE THREAD

**Issue by kyoobey** [Overpeek/fontsdf#1]
expose the [fontdue::Font::chars](https://docs.rs/fontdue/latest/fontdue/struct.Font.html#method.chars) method which is useful in constructing font atlas and caches

**Comment by xor-bits** [comment]
You could access [fontdue::Font::chars](https://docs.rs/fontdue/latest/fontdue/struct.Font.html#method.chars) and other methods with [fontsdf::Font::inner](https://docs.rs/fontsdf/latest/fontsdf/struct.Font.html#method.inner) but I added that `chars` delegate method for [fontdue::Font::chars](https://docs.rs/fontdue/latest/fontdue/struct.Font.html#method.chars).

**Comment by kyoobey** [comment]
well that was quick, thank you for this awesome no_std crate !
